### PR TITLE
Homepage url on logo

### PR DESCRIPTION
**Pull request by lelbil**
Started This following issue [#29](https://github.com/fus-marcom/franciscan-react/issues/29) started by @MrNime

This adds a NextJs `Link` component as suggested by @SebastianCApostolescu in the issue, to the `AppBar`, I also added the test for it. I also changed the links that were pointing to @JesseRWeigel 's last project in `README.md` so they point to this project instead. 

This is my first ever open source PR, and my first ever front end contribution to a real project as well, so any feed back is appreciated, I hope I did everything correct :) Thanks

### CODE REVIEW

**Comment by SebastianCApostolescu** [comment]
So let's say that that Jesse will host the site on www.franciscan-react.com... Where will the logo redirect you to? It will redirect you to a different URL which technically doesn't exist unless you have your localhost server running. 

The correct way to return to the home page is to redirect to the root page `<Link href="/">` being '/' the root of the website (aka homepage).

**Comment by MrNime** [comment]
Yup, doing it that way also won't cause a full page reload.
This also mean the test will change (not a tag anymore, or is there, in the html?)

**Comment by lelbil** [comment]
@SebastianCApostolescu , @MrNime Thanks 👍 

I changed that 

@MrNime it will be a `<a>` in the html (according to my inspector lol)

**Comment by MrNime** [comment]
Don't know much about testing (yet!).
The `<a>` tag inside the JSX in React shouldn't be needed anymore I think.

**Comment by lelbil** [comment]
I tried without the `<a>` tag, it didn't work.

**Comment by SebastianCApostolescu** [comment]
Seems like `NextJS` needs both `<Link>` component and the `<a>` tag.

**Comment by MrNime** [comment]
Yeah, was confusing it with react-router, my bad.
Has anyone found decent documentation for NextJS?

**Comment by JesseRWeigel** [comment]
Thank you @lelbil !

**Pull request merged**
