### PR TITLE
Added Linting and precommit

### LINKED ISSUE #6: Add autoformatting on commit
All code should have to pass StandardJS rules and be auto-formatted on commit.

### PR DESCRIPTION
**Pull request by pantharshit00**
Closes #6 
Added standerd JS rules precommit and husky

### CODE REVIEW

**Comment by MrNime** [comment]
How about using the AirBNB style guide (full-react-version) from the start?
Without an eslinrc file run `./node_modules/.bin/eslint --init` and choose the airbnb option from `use a popular styleguide`

**Comment by pantharshit00** [comment]
@MrNime I appreciate your comment but as @JesseRWeigel doesn't use linter in his code editor airbnb rules will surely piss him off when he will commit lol. Airbnb even errors you out if you don't put methods in right order. Standered JS rules are not that hard

**Comment by MrNime** [comment]
Ah yes, without redsquiggly lines in your editor window it will be very frustrating.
`"react/sort-comp": 0` rule to disable method order rule.

**Comment by JesseRWeigel** [comment]
Yes, I did check out the AirBnB style guide recently. I liked it, but I like Standard better and am more familiar with it.

Also, @pantharshit00 I recently set up StandardJS linting for my editor, so I will have the red squigglies!

**Pull request merged**
